### ISSUE TITLE
error in documentation

### ISSUE THREAD

**Issue by VidJa** [foerstner-lab/gffpandas#1]
* pandasgff version:
* Python version:
* Operating System:

### Description
In https://gffpandas.readthedocs.io/en/latest/background.html there is a link to a local file
'How to use gffpandas'. It links to file:///home/vivian/gffPandas/gffpandas/docs/build/html/tutorial.html

**Comment by VivianMonzon** [comment]
Many thanks and sorry for the late response. It is solved now.
