### ISSUE TITLE
Parse column attributes

### ISSUE THREAD

**Issue by rplanel** [foerstner-lab/gffpandas#4]
* pandasgff version: 1.2.0
* Python version: 3.7.3
* Operating System: Gnu/Linux

### Description

Parse the gff : [GCF_000005845.2_ASM584v2_genomic.gff.gz](ftp://ftp.ncbi.nih.gov/genomes/refseq/bacteria/Escherichia_coli/reference/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.gff.gz)

Cannot parse the attributes column. There is an extra `=` in this column.

The line that makes gffpandas crash is like : 
```
NC_000913.3	RefSeq	CDS	257829	257899	.	+	0	ID=cds-gnl|b0240|CDS=288;Parent=gene-b0240;Dbxref=ASAP:ABE-0000821,ECOCYC:EG11092,EcoGene:EG11092,GeneID:945077;gbkey=CDS;gene=crl;locus_tag=b0240;orig_protein_id=gnl|b0240|CDS%3D288;orig_transcript_id=gnl|b0240|mrna.CDS%3D288;product=RNA polymerase holoenzyme assembly factor Crl;transl_table=11
```
More precisely, this is this part : `ID=cds-gnl|b0240|CDS=288;` that contains an extra `=`

### What I Did

``` python
import gffpandas.gffpandas as gffpd
annotation = gffpd.read_gff3(genome_path)
annotation = annotation.attributes_to_columns()
```

This can be fixed by replacing `key_value_pair.split('=')` by `key_value_pair.split('=', 1)` in the function `attributes_to_columns`

However, I'm not sure it is a good solution :)

I can create a PR for that if you agree.

**Comment by konrad** [comment]
Many thanks for reporting this, @rplanel! Your precise description of the problem and its solution helped us a lot!

**Comment by rplanel** [comment]
You're welcome ! 
Do you consider publishing it on pypi ?

**Comment by konrad** [comment]
Yes, we will do this soon and also extend the library further. Many thanks for your interest!
