### ISSUE TITLE
remove pytest-runner dependency

### ISSUE THREAD

**Issue by joelb123** [foerstner-lab/gffpandas#7]
gffpandas has pytest-runner as a setup_requires hard dependency, meaning that setup will fail without pytest-runner installed, even though pytest-runner is only needed for testing. gffpandas shares this unusual feature with code like screed, which points to a common ancestor.

pytest-runner is deprecated because it has security vulnerabilities.  It's broken with the latest versions of setuptools anyway.  If you remove the line 'pytest-runner' in setup.py, the package will build properly.

**Comment by elhossary** [comment]
Thanks for pointing this out,
we have removed pytest-runner in the current version

**Comment by joelb123** [comment]
Please bump the version number and push the package to pypi.  Until that is done, the old version is still the one that pip installs.
